name: Run tests

on:
  push:
    tags-ignore:
      - '**'

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '8.2'
            composer: 'composer'
          - php: '8.1'
            composer: 'composer'
          - php: '8.0'
            composer: 'composer'
          - php: '7.4'
            composer: 'composer'
          - php: '7.3'
            composer: 'composer'
          - php: '7.2'
            composer: 'composer'
          - php: '7.1'
            composer: 'composer:2.2'
          - php: '7.0'
            composer: 'composer:2.2'
          - php: '5.6'
            composer: 'composer:2.2'
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: "${{ matrix.composer }}"

      - name: Require doctrine/lexer 1.x
        if: "${{ matrix.php == '7.1' }}"
        run: composer require doctrine/lexer ^1.0

      - name: Run composer update
        run: composer update

      - name: Run PHPUnit tests
        run: vendor/bin/simple-phpunit --coverage-text
